
// import './globals.css'

// import { type Metadata } from 'next'
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton>
//                 <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
//                   Sign Up
//                 </button>
//               </SignUpButton>
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }
// import { ClerkProvider } from '@clerk/nextjs'
// import { SidebarProvider } from './components/SidebarContext'
// import Header from './components/Header'
// import Sidebar from './components/Sidebar'
// import './globals.css'

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className="bg-black text-white">
//           <SidebarProvider>
//             <Header />

//             <div className="flex">
//               <Sidebar />
//               <main className="flex-1 p-4">{children}</main>
//             </div>
//           </SidebarProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }
// import './globals.css'
// import { SidebarProvider } from './components/SidebarContext'
// import ClientLayout from './components/ClientLayout'

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <SidebarProvider>
//           <ClientLayout>{children}</ClientLayout>
//         </SidebarProvider>
//       </body>
//     </html>
//   )
// }
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import ClientLayout from "./components/ClientLayout"
import { SidebarProvider } from "./components/SidebarContext"
import UserSync from "./components/UserSync"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          < UserSync />
          <SidebarProvider>
            <ClientLayout>{children}</ClientLayout>
          </SidebarProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
